### ISSUE TITLE
Chakra discontinued

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#176] opened 2020-10-27 11:54 UTC
* Name: Chakra
* Discontinuation statement URL if available
https://distrowatch.com/table.php?distribution=chakra

**Comment by FabioLolix** [comment] 2022-01-03 16:38
I left this open because while iso images have not been published for a while at first sight packages where still updated, with today distrowatch weekly have been reported that it is effectively discontinued and website took offline (confirmed)

**Comment by FabioLolix** [comment] 2022-01-10 15:49
Fixed with https://github.com/FabioLolix/LinuxTimeline/commit/75a1087894de0197496f30800e3a4bfa69688bcb

**Closed by FabioLolix** 2022-01-10 15:49 UTC
