### ISSUE TITLE
Red Hat Enterprise is based on Fedora

### ISSUE THREAD

**Issue by CodeDoctorDE** [FabioLolix/LinuxTimeline#181] opened 2020-11-01 14:08 UTC
* Name: Red Hat Enterprise

## Issue

The newest red hat enterprise is based on fedora: https://docs.fedoraproject.org/en-US/quick-docs/fedora-and-red-hat-enterprise-linux/#_history_of_red_hat_enterprise_linux_and_fedora

**Comment by FabioLolix** [comment] 2020-11-01 14:19
Duplicate of #66

**Closed by FabioLolix** 2020-11-01 14:19 UTC
